version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16  # Use an appropriate Node.js version

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Linting (ESLint)
          command: |
            npx eslint . || echo "Linting issues detected, but continuing..."
      - run:
          name: Run Tests (Skip if not available)
          command: npm test || echo "No tests found, skipping..."

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install SSH Client
          command: sudo apt update && sudo apt install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - "SHA256:xr2YeW2BrstynvgcjkicFSKC6jEWFmrtliNprXrkgc8"
      - run:
          name: Deploy to AWS EC2
          command: |
            echo "Deploying to EC2..."
            
            # Copy project files to EC2 instance
            scp -o StrictHostKeyChecking=no -r * ubuntu@$EC2_HOST:/var/www/html/

            # SSH into EC2 and configure the application
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "bash -c '
              cd /var/www/html
              npm install
              pm2 restart app.js || pm2 start app.js --name node-app
            '"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main  # Deploy only from the main branch
